### ISSUE TITLE
swiping empty recycler causes crash

### ISSUE THREAD

**Issue by ericcumbee** [rahulrj/Swipe_RecyclerView#3]
Just playing with my app, i noticed that if you swipe an empty swiperecycler it crashes with 

`java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at com.fortysevendeg.swipelistview.SwipeListViewTouchListener.closeOtherOpenedItems(SwipeListViewTouchListener.java:997)
            at com.fortysevendeg.swipelistview.SwipeListViewTouchListener.onTouch(SwipeListViewTouchListener.java:985)`

I can post additional code/details tomorrow, but just wanted to put this in before I forgot.

**Comment by rahulrj** [comment]
I will look into it and update it. Was just too busy, so took time to notice the issue.
Thanks.

**Comment by u2gilles** [comment]
Hi Rahulrj, 

It would be great if you could find some time to fix this issue.

In the meanwhile, I added the following quick fix in " in closeOpenedItems() and  closeOtherOpenedItems() methods of  your lib and recompiled it locally :  "if (start==-1) return;"

Also could you please add this lib in a Marven repo and if possible use versions.

Thanks in Advance.

**Comment by rahulrj** [comment]
Okay. Will do on the coming Thursday as its a holiday.

**Comment by u2gilles** [comment]
Good. I'm afraid my fix has side effects . Better a clean fix from the designer

Sent from Samsung Mobile.

<div>-------- Original message --------</div><div>From: RAHUL RAJA notifications@github.com </div><div>Date:13/01/2015  23:51  (GMT+07:00) </div><div>To: rahulrj/Swipe_RecyclerView Swipe_RecyclerView@noreply.github.com </div><div>Cc: u2gilles u2gilles@gmail.com </div><div>Subject: Re: [Swipe_RecyclerView] swiping empty recycler causes crash (#3) </div><div>
</div>Okay. Will do on the coming Thursday as its a holiday.

**Comment by bvanhou** [comment]
I am running into the same issue. Attempting to figure out a fix though do not seem to be succeeding. 

01-18 23:10:29.329    1264-1264/com.drinkapp.drink E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
01-18 23:10:29.349    1264-1264/com.drinkapp.drink E/MessageQueue-JNI﹕ java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.fortysevendeg.swipelistview.SwipeListViewTouchListener.closeOtherOpenedItems(SwipeListViewTouchListener.java:1000)
            at com.fortysevendeg.swipelistview.SwipeListViewTouchListener.onTouch(SwipeListViewTouchListener.java:986)

**Comment by u2gilles** [comment]
We may not use the lib in the same way. I recommend you to use a debugger and notice that when start==-1, it crashed. Then add your own fix to make it works until Rahulrj provides the final patch.  .
