### ISSUE TITLE
 NullPointerException at setFrontView(SwipeListViewTouchListener.java:151)

### ISSUE THREAD

**Issue by u2gilles** [rahulrj/Swipe_RecyclerView#5]
Hi Rahul Raja,

I successfully run the Swipe_RecyclerView demo .
But in my app , when i touch any list item of a SwipeRecyclerView, I have a NullPointerException at SwipeListViewTouchListener.setFrontView(SwipeListViewTouchListener.java:151)

Have you see this error before? Can you see what I missed from your experience?

Kind regards,
Gilles
# TRACE OF THE ERROR :

12-31 13:04:53.460    5721-5721/com.me.template1 E/InputEventReceiver﹕ Exception dispatching input event.
12-31 13:04:53.460    5721-5721/com.me.template1 E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
12-31 13:04:53.470    5721-5721/com.me.template1 E/MessageQueue-JNI﹕ java.lang.NullPointerException
            at com.fortysevendeg.swipelistview.SwipeListViewTouchListener.setFrontView(SwipeListViewTouchListener.java:151)
            at com.fortysevendeg.swipelistview.SwipeListViewTouchListener.onTouch(SwipeListViewTouchListener.java:827)
            at com.fortysevendeg.swipelistview.SwipeListView.onInterceptTouchEvent(SwipeListView.java:687)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2043)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2411)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2101)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2280)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1615)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2549)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2228)
            at android.view.View.dispatchPointerEvent(View.java:8315)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4597)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4465)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4023)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4077)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4046)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4157)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4054)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4214)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4023)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4077)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4046)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4054)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4023)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6404)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6308)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6279)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6244)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6484)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:138)
            at android.os.Looper.loop(Looper.java:123)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by u2gilles** [comment]
It was just a typo in the code.  I inflated the wrong layout in onCreateViewHolder()
